meta_product_name: "Pilotis"
meta_title: "Pilotis -Pilotis - Manage your Scouting community seamlessly, from one unified place"
meta_description: "Pilotis let you manage your organisation from one unified place and get a grip on (i) your user community, (ii) an overview of your invoices, (iii) share your photos in a secured way "
meta_image: "pendingbck.jpg" # should exist in `app/assets/images/`
